# Form implementation generated from reading ui file 'man_hinh_them_cau_hoi.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resource

class Ui_man_hinh_them_cau_hoi(object):
    def setupUi(self, man_hinh_them_cau_hoi):
        man_hinh_them_cau_hoi.setObjectName("man_hinh_them_cau_hoi")
        man_hinh_them_cau_hoi.resize(960, 540)
        self.gridLayout = QtWidgets.QGridLayout(man_hinh_them_cau_hoi)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=man_hinh_them_cau_hoi)
        self.groupBox.setStyleSheet("border: 3px solid rgb(0, 112, 192);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 50, -1, 30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setStyleSheet("border: None;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(0, 50, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.do_kho = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.do_kho.setGeometry(QtCore.QRect(70, 45, 111, 31))
        self.do_kho.setStyleSheet("border: 2px solid rgba(46, 82, 101, 200);\n"
"")
        self.do_kho.setObjectName("do_kho")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_4.setStyleSheet("border: None;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.diem = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.diem.setGeometry(QtCore.QRect(70, 26, 111, 31))
        self.diem.setStyleSheet("border: 2px solid rgba(46, 82, 101, 200);\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 16px;")
        self.diem.setObjectName("diem")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_5.setStyleSheet("border: None;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.them = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.them.setGeometry(QtCore.QRect(20, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.them.setFont(font)
        self.them.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(85, 170, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/6_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.them.setIcon(icon)
        self.them.setObjectName("them")
        self.thoat = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.thoat.setGeometry(QtCore.QRect(20, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(85, 170, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/32_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.thoat.setIcon(icon1)
        self.thoat.setObjectName("thoat")
        self.tim_kiem = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.tim_kiem.setGeometry(QtCore.QRect(20, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.tim_kiem.setFont(font)
        self.tim_kiem.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(85, 170, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/893_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.tim_kiem.setIcon(icon2)
        self.tim_kiem.setObjectName("tim_kiem")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=man_hinh_them_cau_hoi)
        self.groupBox_2.setStyleSheet("border: 3px solid rgb(0, 112, 192);\n"
"border-radius: 10px;\n"
"background-color:rgb(0, 112, 192);\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.danh_sach_cau_hoi = QtWidgets.QTableWidget(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.danh_sach_cau_hoi.setFont(font)
        self.danh_sach_cau_hoi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: None;\n"
"border-radius: 0px;\n"
"")
        self.danh_sach_cau_hoi.setObjectName("danh_sach_cau_hoi")
        self.danh_sach_cau_hoi.setColumnCount(0)
        self.danh_sach_cau_hoi.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.danh_sach_cau_hoi)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(man_hinh_them_cau_hoi)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_them_cau_hoi)

    def retranslateUi(self, man_hinh_them_cau_hoi):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_them_cau_hoi.setWindowTitle(_translate("man_hinh_them_cau_hoi", "Dialog"))
        self.label.setText(_translate("man_hinh_them_cau_hoi", "Độ khó"))
        self.label_2.setText(_translate("man_hinh_them_cau_hoi", "Điểm"))
        self.them.setText(_translate("man_hinh_them_cau_hoi", "Thêm"))
        self.thoat.setText(_translate("man_hinh_them_cau_hoi", "Thoát"))
        self.tim_kiem.setText(_translate("man_hinh_them_cau_hoi", "Tìm kiếm"))
