# Form implementation generated from reading ui file 'man_hinh_chinh.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resource

class Ui_man_hinh_chinh(object):
    def setupUi(self, man_hinh_chinh):
        man_hinh_chinh.setObjectName("man_hinh_chinh")
        man_hinh_chinh.resize(960, 540)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        man_hinh_chinh.setFont(font)
        man_hinh_chinh.setToolTipDuration(-2)
        man_hinh_chinh.setStyleSheet("")
        self.danh_sach_cau_hoi = QtWidgets.QPushButton(parent=man_hinh_chinh)
        self.danh_sach_cau_hoi.setGeometry(QtCore.QRect(360, 240, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.danh_sach_cau_hoi.setFont(font)
        self.danh_sach_cau_hoi.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 45, 157);\n"
"    border-radius: 30%\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Ảnh10.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.danh_sach_cau_hoi.setIcon(icon)
        self.danh_sach_cau_hoi.setObjectName("danh_sach_cau_hoi")
        self.danh_sach_de_thi = QtWidgets.QPushButton(parent=man_hinh_chinh)
        self.danh_sach_de_thi.setGeometry(QtCore.QRect(370, 170, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.danh_sach_de_thi.setFont(font)
        self.danh_sach_de_thi.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"background-color: rgb(48, 45, 157);\n"
"    border-radius: 30%\n"
"}")
        self.danh_sach_de_thi.setIcon(icon)
        self.danh_sach_de_thi.setObjectName("danh_sach_de_thi")
        self.bao_cao_nam = QtWidgets.QPushButton(parent=man_hinh_chinh)
        self.bao_cao_nam.setGeometry(QtCore.QRect(390, 380, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.bao_cao_nam.setFont(font)
        self.bao_cao_nam.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 45, 157);\n"
"    border-radius: 30%\n"
"}")
        self.bao_cao_nam.setIcon(icon)
        self.bao_cao_nam.setObjectName("bao_cao_nam")
        self.danh_sach_cham_thi = QtWidgets.QPushButton(parent=man_hinh_chinh)
        self.danh_sach_cham_thi.setGeometry(QtCore.QRect(370, 310, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.danh_sach_cham_thi.setFont(font)
        self.danh_sach_cham_thi.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 45, 157);\n"
"    border-radius: 30%\n"
"}")
        self.danh_sach_cham_thi.setIcon(icon)
        self.danh_sach_cham_thi.setObjectName("danh_sach_cham_thi")
        self.label = QtWidgets.QLabel(parent=man_hinh_chinh)
        self.label.setGeometry(QtCore.QRect(210, 40, 621, 111))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 30%;\n"
"background-color: rgb(48, 45, 157);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.dang_xuat = QtWidgets.QPushButton(parent=man_hinh_chinh)
        self.dang_xuat.setGeometry(QtCore.QRect(790, 460, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.dang_xuat.setFont(font)
        self.dang_xuat.setStyleSheet("background-color: rgb(48, 45, 157);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30%;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/22_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dang_xuat.setIcon(icon1)
        self.dang_xuat.setObjectName("dang_xuat")
        self.label_2 = QtWidgets.QLabel(parent=man_hinh_chinh)
        self.label_2.setGeometry(QtCore.QRect(550, -140, 800, 800))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/Hình tròn.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=man_hinh_chinh)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(50, 40, 121, 111))
        self.label_4.setMouseTracking(False)
        self.label_4.setTabletTracking(False)
        self.label_4.setAcceptDrops(False)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/images/trang chủ hình nón.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=man_hinh_chinh)
        self.label_5.setGeometry(QtCore.QRect(-120, 319, 311, 301))
        self.label_5.setStyleSheet("border-radius:100%")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/Hình tròn.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(parent=man_hinh_chinh)
        self.label_3.setGeometry(QtCore.QRect(-140, 500, 431, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/Ảnh17.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=man_hinh_chinh)
        self.label_6.setGeometry(QtCore.QRect(-210, 430, 431, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/Ảnh17.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_2.raise_()
        self.danh_sach_cau_hoi.raise_()
        self.danh_sach_de_thi.raise_()
        self.bao_cao_nam.raise_()
        self.danh_sach_cham_thi.raise_()
        self.dang_xuat.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()

        self.retranslateUi(man_hinh_chinh)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_chinh)

    def retranslateUi(self, man_hinh_chinh):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_chinh.setWindowTitle(_translate("man_hinh_chinh", "Form"))
        self.danh_sach_cau_hoi.setText(_translate("man_hinh_chinh", "Kho câu hỏi"))
        self.danh_sach_de_thi.setText(_translate("man_hinh_chinh", "Kho đề thi"))
        self.bao_cao_nam.setText(_translate("man_hinh_chinh", "Báo cáo năm"))
        self.danh_sach_cham_thi.setText(_translate("man_hinh_chinh", "Chấm thi"))
        self.label.setText(_translate("man_hinh_chinh", "<html><head/><body><p align=\"center\">PHẦN MỀM QUẢN LÍ VIỆC RA ĐỀ VÀ </p><p align=\"center\">CHẤM THI CHO GIẢNG VIÊN</p></body></html>"))
        self.dang_xuat.setText(_translate("man_hinh_chinh", "Đăng xuất"))
