# Form implementation generated from reading ui file 'man_hinh_bao_cao_nam.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resource

class Ui_man_hinh_bao_cao_nam(object):
    def setupUi(self, man_hinh_bao_cao_nam):
        man_hinh_bao_cao_nam.setObjectName("man_hinh_bao_cao_nam")
        man_hinh_bao_cao_nam.resize(960, 540)
        self.verticalLayout = QtWidgets.QVBoxLayout(man_hinh_bao_cao_nam)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=man_hinh_bao_cao_nam)
        self.groupBox.setStyleSheet("border: None;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, -4, 951, 701))
        self.groupBox_2.setStyleSheet("border: None;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_5.setStyleSheet("border: None;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox_5)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 181, 501))
        self.groupBox_3.setStyleSheet("border: 3px solid rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"border-color: rgb(0, 112, 192);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.xuat = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.xuat.setGeometry(QtCore.QRect(30, 340, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.xuat.setFont(font)
        self.xuat.setStyleSheet("\n"
"background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/334_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.xuat.setIcon(icon)
        self.xuat.setObjectName("xuat")
        self.thoat = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.thoat.setGeometry(QtCore.QRect(30, 400, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/32_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.thoat.setIcon(icon1)
        self.thoat.setObjectName("thoat")
        self.nam_hoc = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.nam_hoc.setGeometry(QtCore.QRect(30, 210, 121, 31))
        self.nam_hoc.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"")
        self.nam_hoc.setObjectName("nam_hoc")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(30, 185, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:  rgb(253, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 131))
        self.label.setStyleSheet("\n"
"background-color: rgb(253, 255, 255);\n"
"border-color: rgb(253, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/333691756_871094670849167_873075225703648657_n.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tao = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.tao.setGeometry(QtCore.QRect(30, 280, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.tao.setFont(font)
        self.tao.setStyleSheet("\n"
"background-color: rgb(85, 170, 255);\n"
"border-color: rgb(0, 0, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/6_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tao.setIcon(icon2)
        self.tao.setObjectName("tao")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(190, 0, 731, 501))
        self.groupBox_7.setStyleSheet("border: 2.5px solid rgb(0, 112, 192);\n"
"border-color: rgb(0, 112, 192);\n"
"background-color: rgb(0, 112, 192);\n"
"border-radius: 10px\n"
"")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 50, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"border-radius: 10px;\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.tong_so_de_thi = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.tong_so_de_thi.setGeometry(QtCore.QRect(140, 10, 111, 41))
        self.tong_so_de_thi.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 16px;")
        self.tong_so_de_thi.setObjectName("tong_so_de_thi")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.groupBox_7)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 50, 331, 61))
        self.groupBox_6.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"border-radius: 10px;\n"
"")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.tong_so_bai_cham = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.tong_so_bai_cham.setGeometry(QtCore.QRect(170, 10, 111, 41))
        self.tong_so_bai_cham.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"selection-background-color: darkgray;\n"
"font-size: 16px;")
        self.tong_so_bai_cham.setObjectName("tong_so_bai_cham")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:  rgb(253, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.groupBox_7)
        self.textEdit.setGeometry(QtCore.QRect(230, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border-color: rgb(253, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.bao_cao_nam = QtWidgets.QTableWidget(parent=self.groupBox_7)
        self.bao_cao_nam.setGeometry(QtCore.QRect(10, 131, 711, 361))
        self.bao_cao_nam.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0, 112, 192);")
        self.bao_cao_nam.setObjectName("bao_cao_nam")
        self.bao_cao_nam.setColumnCount(0)
        self.bao_cao_nam.setRowCount(0)
        self.groupBox_7.raise_()
        self.groupBox_3.raise_()
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(man_hinh_bao_cao_nam)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_bao_cao_nam)

    def retranslateUi(self, man_hinh_bao_cao_nam):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_bao_cao_nam.setWindowTitle(_translate("man_hinh_bao_cao_nam", "Form"))
        self.xuat.setText(_translate("man_hinh_bao_cao_nam", "Xuất File"))
        self.thoat.setText(_translate("man_hinh_bao_cao_nam", "Thoát"))
        self.label_4.setText(_translate("man_hinh_bao_cao_nam", "Năm học:"))
        self.tao.setText(_translate("man_hinh_bao_cao_nam", "Tạo"))
        self.label_2.setText(_translate("man_hinh_bao_cao_nam", "Tổng số đề thi:"))
        self.label_3.setText(_translate("man_hinh_bao_cao_nam", "Tổng số bài chấm: "))
        self.textEdit.setHtml(_translate("man_hinh_bao_cao_nam", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Tahoma\'; font-size:12pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:16pt; font-weight:696;\">BÁO CÁO NĂM</span></p></body></html>"))
