# Form implementation generated from reading ui file 'man_hinh_lap_ket_qua_cham_thi.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import resource

class Ui_man_hinh_lap_ket_qua_cham_thi(object):
    def setupUi(self, man_hinh_lap_ket_qua_cham_thi):
        man_hinh_lap_ket_qua_cham_thi.setObjectName("man_hinh_lap_ket_qua_cham_thi")
        man_hinh_lap_ket_qua_cham_thi.resize(960, 540)
        man_hinh_lap_ket_qua_cham_thi.setStyleSheet("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=man_hinh_lap_ket_qua_cham_thi)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 10, 581, 85))
        self.groupBox_2.setStyleSheet("border:None;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.ten_giang_vien = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.ten_giang_vien.setGeometry(QtCore.QRect(250, 25, 291, 31))
        self.ten_giang_vien.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border: 2px solid rgba(46, 82, 101, 200);\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"font-size: 16px;")
        self.ten_giang_vien.setObjectName("ten_giang_vien")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 561, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/Ảnh26.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 55, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/sinh viên.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(80, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: None;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_2.raise_()
        self.ten_giang_vien.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.groupBox = QtWidgets.QGroupBox(parent=man_hinh_lap_ket_qua_cham_thi)
        self.groupBox.setGeometry(QtCore.QRect(11, 11, 231, 511))
        self.groupBox.setStyleSheet("border: 3px solid rgba(46, 82, 101, 200);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0, 112, 192);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_4.setStyleSheet("border: None;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lop_hoc = QtWidgets.QComboBox(parent=self.groupBox_4)
        self.lop_hoc.setGeometry(QtCore.QRect(10, 40, 171, 31))
        self.lop_hoc.setStyleSheet("border: 2px solid rgba(46, 82, 101, 200);\n"
"")
        self.lop_hoc.setObjectName("lop_hoc")
        self.label = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_5.setStyleSheet("border: None;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.mon_hoc = QtWidgets.QComboBox(parent=self.groupBox_5)
        self.mon_hoc.setGeometry(QtCore.QRect(10, 40, 171, 31))
        self.mon_hoc.setStyleSheet("border: 2px solid rgba(46, 82, 101, 200);\n"
"")
        self.mon_hoc.setObjectName("mon_hoc")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_6.setStyleSheet("border: None;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.ma_de = QtWidgets.QComboBox(parent=self.groupBox_6)
        self.ma_de.setGeometry(QtCore.QRect(10, 40, 171, 31))
        self.ma_de.setStyleSheet("border: 2px solid rgba(46, 82, 101, 200);\n"
"")
        self.ma_de.setObjectName("ma_de")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_7.setStyleSheet("border: None;")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.them = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.them.setGeometry(QtCore.QRect(10, 100, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.them.setFont(font)
        self.them.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;border: 2px solid rgb(0,0,0)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/6_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("../../../cnpm/6_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.them.setIcon(icon)
        self.them.setObjectName("them")
        self.thoat = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.thoat.setGeometry(QtCore.QRect(10, 150, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;border: 2px solid rgb(0,0,0)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/32_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap("../../../cnpm/32_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.thoat.setIcon(icon1)
        self.thoat.setObjectName("thoat")
        self.tim_kiem = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.tim_kiem.setGeometry(QtCore.QRect(10, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        self.tim_kiem.setFont(font)
        self.tim_kiem.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(0,0,0)")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/893_n.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.tim_kiem.setIcon(icon2)
        self.tim_kiem.setObjectName("tim_kiem")
        self.verticalLayout.addWidget(self.groupBox_7)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 3)
        self.textEdit = QtWidgets.QTextEdit(parent=man_hinh_lap_ket_qua_cham_thi)
        self.textEdit.setGeometry(QtCore.QRect(410, 100, 391, 31))
        self.textEdit.setStyleSheet("border:none;")
        self.textEdit.setObjectName("textEdit")
        self.ket_qua_cham_thi = QtWidgets.QTableWidget(parent=man_hinh_lap_ket_qua_cham_thi)
        self.ket_qua_cham_thi.setEnabled(True)
        self.ket_qua_cham_thi.setGeometry(QtCore.QRect(250, 140, 691, 381))
        self.ket_qua_cham_thi.setAcceptDrops(False)
        self.ket_qua_cham_thi.setStyleSheet("border: 1px solid rgba(46, 82, 101, 200);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"border-color: rgb(0, 112, 192);")
        self.ket_qua_cham_thi.setAutoScroll(True)
        self.ket_qua_cham_thi.setProperty("showDropIndicator", True)
        self.ket_qua_cham_thi.setDragDropOverwriteMode(True)
        self.ket_qua_cham_thi.setShowGrid(True)
        self.ket_qua_cham_thi.setObjectName("ket_qua_cham_thi")
        self.ket_qua_cham_thi.setColumnCount(0)
        self.ket_qua_cham_thi.setRowCount(0)
        self.ket_qua_cham_thi.horizontalHeader().setHighlightSections(True)
        self.ket_qua_cham_thi.verticalHeader().setHighlightSections(True)

        self.retranslateUi(man_hinh_lap_ket_qua_cham_thi)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_lap_ket_qua_cham_thi)

    def retranslateUi(self, man_hinh_lap_ket_qua_cham_thi):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_lap_ket_qua_cham_thi.setWindowTitle(_translate("man_hinh_lap_ket_qua_cham_thi", "Form"))
        self.label_6.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Tên giảng viên:"))
        self.label.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Lớp học: "))
        self.label_4.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Môn học:"))
        self.label_5.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Mã đề:"))
        self.them.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Thêm"))
        self.thoat.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Thoát"))
        self.tim_kiem.setText(_translate("man_hinh_lap_ket_qua_cham_thi", "Tìm kiếm"))
        self.textEdit.setHtml(_translate("man_hinh_lap_ket_qua_cham_thi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">DANH SÁCH NHẬP ĐIỂM THI</span></p></body></html>"))
