# Form implementation generated from reading ui file 'man_hinh_dang_nhap.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_man_hinh_dang_nhap(object):
    def setupUi(self, man_hinh_dang_nhap):
        man_hinh_dang_nhap.setObjectName("man_hinh_dang_nhap")
        man_hinh_dang_nhap.resize(600, 500)
        self.widget_dang_nhap = QtWidgets.QWidget(parent=man_hinh_dang_nhap)
        self.widget_dang_nhap.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.widget_dang_nhap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_dang_nhap.setObjectName("widget_dang_nhap")
        self.label = QtWidgets.QLabel(parent=self.widget_dang_nhap)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 500))
        self.label.setStyleSheet("border-image: url(:/images/uit.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_dang_nhap)
        self.label_2.setGeometry(QtCore.QRect(360, 60, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tai_khoan = QtWidgets.QLineEdit(parent=self.widget_dang_nhap)
        self.tai_khoan.setGeometry(QtCore.QRect(340, 140, 210, 30))
        self.tai_khoan.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"")
        self.tai_khoan.setInputMask("")
        self.tai_khoan.setText("")
        self.tai_khoan.setObjectName("tai_khoan")
        self.mat_khau = QtWidgets.QLineEdit(parent=self.widget_dang_nhap)
        self.mat_khau.setGeometry(QtCore.QRect(340, 210, 210, 30))
        self.mat_khau.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color: rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;\n"
"")
        self.mat_khau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.mat_khau.setObjectName("mat_khau")
        self.dang_nhap = QtWidgets.QPushButton(parent=self.widget_dang_nhap)
        self.dang_nhap.setGeometry(QtCore.QRect(340, 310, 210, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        self.dang_nhap.setFont(font)
        self.dang_nhap.setStyleSheet("background-color: rgba(46, 82, 101, 200);\n"
"border-color: rgba(0, 0, 0, 0);")
        self.dang_nhap.setObjectName("dang_nhap")
        self.thoat = QtWidgets.QPushButton(parent=self.widget_dang_nhap)
        self.thoat.setGeometry(QtCore.QRect(340, 380, 210, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("background-color: rgba(46, 82, 101, 200);\n"
"border-color: rgba(0, 0, 0, 0);")
        self.thoat.setObjectName("thoat")
        self.hien_mat_khau = QtWidgets.QCheckBox(parent=self.widget_dang_nhap)
        self.hien_mat_khau.setGeometry(QtCore.QRect(537, 210, 16, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hien_mat_khau.sizePolicy().hasHeightForWidth())
        self.hien_mat_khau.setSizePolicy(sizePolicy)
        self.hien_mat_khau.setText("")
        self.hien_mat_khau.setObjectName("hien_mat_khau")

        self.retranslateUi(man_hinh_dang_nhap)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_dang_nhap)

    def retranslateUi(self, man_hinh_dang_nhap):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_dang_nhap.setWindowTitle(_translate("man_hinh_dang_nhap", "Form"))
        self.label_2.setText(_translate("man_hinh_dang_nhap", "ĐĂNG NHẬP"))
        self.tai_khoan.setPlaceholderText(_translate("man_hinh_dang_nhap", "Nhập Tài khoản"))
        self.mat_khau.setPlaceholderText(_translate("man_hinh_dang_nhap", "Nhập mật khẩu"))
        self.dang_nhap.setText(_translate("man_hinh_dang_nhap", "Đăng nhập"))
        self.thoat.setText(_translate("man_hinh_dang_nhap", "Thoát"))
