# Form implementation generated from reading ui file 'man_hinh_sua_admin.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_man_hinh_sua_admin(object):
    def setupUi(self, man_hinh_sua_admin):
        man_hinh_sua_admin.setObjectName("man_hinh_sua_admin")
        man_hinh_sua_admin.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=man_hinh_sua_admin)
        self.label.setGeometry(QtCore.QRect(50, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;")
        self.label.setObjectName("label")
        self.ten_tai_khoan = QtWidgets.QLineEdit(parent=man_hinh_sua_admin)
        self.ten_tai_khoan.setGeometry(QtCore.QRect(170, 70, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.ten_tai_khoan.setFont(font)
        self.ten_tai_khoan.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.ten_tai_khoan.setObjectName("ten_tai_khoan")
        self.label_8 = QtWidgets.QLabel(parent=man_hinh_sua_admin)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.label_8.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.thoat = QtWidgets.QPushButton(parent=man_hinh_sua_admin)
        self.thoat.setGeometry(QtCore.QRect(280, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(255, 85, 0);\n"
"border-radius: 5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/32_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.thoat.setIcon(icon)
        self.thoat.setObjectName("thoat")
        self.sua = QtWidgets.QPushButton(parent=man_hinh_sua_admin)
        self.sua.setGeometry(QtCore.QRect(280, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.sua.setFont(font)
        self.sua.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 5px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/334_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.sua.setIcon(icon1)
        self.sua.setObjectName("sua")
        self.label_2 = QtWidgets.QLabel(parent=man_hinh_sua_admin)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;")
        self.label_2.setObjectName("label_2")
        self.mat_khau = QtWidgets.QLineEdit(parent=man_hinh_sua_admin)
        self.mat_khau.setGeometry(QtCore.QRect(170, 120, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.mat_khau.setFont(font)
        self.mat_khau.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.mat_khau.setObjectName("mat_khau")
        self.label_8.raise_()
        self.label.raise_()
        self.ten_tai_khoan.raise_()
        self.thoat.raise_()
        self.sua.raise_()
        self.label_2.raise_()
        self.mat_khau.raise_()

        self.retranslateUi(man_hinh_sua_admin)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_sua_admin)

    def retranslateUi(self, man_hinh_sua_admin):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_sua_admin.setWindowTitle(_translate("man_hinh_sua_admin", "Form"))
        self.label.setText(_translate("man_hinh_sua_admin", "Tên tài khoản"))
        self.thoat.setText(_translate("man_hinh_sua_admin", "THOÁT"))
        self.sua.setText(_translate("man_hinh_sua_admin", "SỬA"))
        self.label_2.setText(_translate("man_hinh_sua_admin", "Mật khẩu"))
