# Form implementation generated from reading ui file 'man_hinh_them_giang_vien.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_man_hinh_them_giang_vien(object):
    def setupUi(self, man_hinh_them_giang_vien):
        man_hinh_them_giang_vien.setObjectName("man_hinh_them_giang_vien")
        man_hinh_them_giang_vien.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=man_hinh_them_giang_vien)
        self.label.setGeometry(QtCore.QRect(30, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;")
        self.label.setObjectName("label")
        self.ten_giang_vien = QtWidgets.QLineEdit(parent=man_hinh_them_giang_vien)
        self.ten_giang_vien.setGeometry(QtCore.QRect(190, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.ten_giang_vien.setFont(font)
        self.ten_giang_vien.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.ten_giang_vien.setObjectName("ten_giang_vien")
        self.label_8 = QtWidgets.QLabel(parent=man_hinh_them_giang_vien)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 381, 281))
        self.label_8.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.thoat = QtWidgets.QPushButton(parent=man_hinh_them_giang_vien)
        self.thoat.setGeometry(QtCore.QRect(280, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.thoat.setFont(font)
        self.thoat.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(255, 85, 0);\n"
"border-radius: 5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/32_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.thoat.setIcon(icon)
        self.thoat.setObjectName("thoat")
        self.them = QtWidgets.QPushButton(parent=man_hinh_them_giang_vien)
        self.them.setGeometry(QtCore.QRect(170, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.them.setFont(font)
        self.them.setStyleSheet("border: 3px solid rgb(0,0,0);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 5px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/6_n.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.them.setIcon(icon1)
        self.them.setObjectName("them")
        self.label_2 = QtWidgets.QLabel(parent=man_hinh_them_giang_vien)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=man_hinh_them_giang_vien)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;")
        self.label_3.setObjectName("label_3")
        self.ten_tai_khoan = QtWidgets.QLineEdit(parent=man_hinh_them_giang_vien)
        self.ten_tai_khoan.setGeometry(QtCore.QRect(190, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.ten_tai_khoan.setFont(font)
        self.ten_tai_khoan.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.ten_tai_khoan.setObjectName("ten_tai_khoan")
        self.mat_khau = QtWidgets.QLineEdit(parent=man_hinh_them_giang_vien)
        self.mat_khau.setGeometry(QtCore.QRect(190, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.mat_khau.setFont(font)
        self.mat_khau.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.mat_khau.setObjectName("mat_khau")
        self.label_4 = QtWidgets.QLabel(parent=man_hinh_them_giang_vien)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setObjectName("label_4")
        self.tinh_trang = QtWidgets.QLineEdit(parent=man_hinh_them_giang_vien)
        self.tinh_trang.setGeometry(QtCore.QRect(190, 190, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.tinh_trang.setFont(font)
        self.tinh_trang.setStyleSheet("border: 2px solid rgb(0, 112, 192);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px")
        self.tinh_trang.setObjectName("tinh_trang")
        self.label_8.raise_()
        self.label.raise_()
        self.ten_giang_vien.raise_()
        self.thoat.raise_()
        self.them.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.ten_tai_khoan.raise_()
        self.mat_khau.raise_()
        self.label_4.raise_()
        self.tinh_trang.raise_()

        self.retranslateUi(man_hinh_them_giang_vien)
        QtCore.QMetaObject.connectSlotsByName(man_hinh_them_giang_vien)

    def retranslateUi(self, man_hinh_them_giang_vien):
        _translate = QtCore.QCoreApplication.translate
        man_hinh_them_giang_vien.setWindowTitle(_translate("man_hinh_them_giang_vien", "Form"))
        self.label.setText(_translate("man_hinh_them_giang_vien", "Tên giảng viên: "))
        self.thoat.setText(_translate("man_hinh_them_giang_vien", "THOÁT"))
        self.them.setText(_translate("man_hinh_them_giang_vien", "THÊM"))
        self.label_2.setText(_translate("man_hinh_them_giang_vien", "Tên tài khoản:"))
        self.label_3.setText(_translate("man_hinh_them_giang_vien", "Mật khẩu:"))
        self.label_4.setText(_translate("man_hinh_them_giang_vien", "Tình trạng:"))
